[package]
name = "reffers"
version = "0.1.0"
authors = ["David Henningsson <diwic@ubuntu.com>"]
license = "Apache-2.0/MIT"
description = "Smart pointer wrappers around references, Boxes and Arcs."
keywords = ["ref", "box", "arc", "pointer", "RMBA", "OwningRef", "ARef"]
repository = "https://github.com/diwic/reffers-rs"
documentation = "http://docs.rs/reffers"

[dependencies]
